Repository AgileGroup6/Agile-Project, pull requests merged in 2023-01, with the labels that each got.

#1 Initializing project
  client/Dockerfile
  client/app/.eslintrc.cjs
  client/app/.gitignore
  client/app/.prettierrc.json
  client/app/.vscode/extensions.json
  client/app/README.md
  client/app/index.html
  client/app/package-lock.json
  client/app/package.json
  client/app/public/favicon.ico
  client/app/src/App.vue
  client/app/src/assets/base.css
  client/app/src/assets/logo.svg
  client/app/src/assets/main.css
  client/app/src/components/HelloWorld.vue
  client/app/src/components/TheWelcome.vue
  client/app/src/components/WelcomeItem.vue
  client/app/src/components/icons/IconCommunity.vue
  client/app/src/components/icons/IconDocumentation.vue
  client/app/src/components/icons/IconEcosystem.vue
  client/app/src/components/icons/IconSupport.vue
  client/app/src/components/icons/IconTooling.vue
  client/app/src/main.js
  client/app/src/router/index.js
  client/app/src/stores/counter.js
  client/app/src/views/AboutView.vue
  client/app/src/views/HomeView.vue
  client/app/vite.config.js
  client/nginx.conf
  docker-compose.yml
  server/Dockerfile
  server/app/api/addNumbers.js
  server/app/api/ping.js
  server/app/config.js
  server/app/errors.js
  server/app/package-lock.json
  server/app/package.json
  server/app/routes.js
  server/app/server.js
Labels: Feature

#3 added pullrequrest template and figma to readme file
  .github/pull_request_template.md
  README.md
Labels: Feature

#6 added .gitignore
  .gitignore
Labels: Bug Fix

#85 display relevant items when a category is selected
  client/app/package-lock.json
  client/app/package.json
  client/app/src/components/browseResults.vue
  client/app/src/components/ingredientCard.vue
  client/app/src/main.js
  client/app/src/views/BrowseView.vue
Labels: Under review

#90 added home page with logo,list and browse all button
  client/app/src/App.vue
  client/app/src/assets/base.css
  client/app/src/assets/logo.svg
  client/app/src/assets/logo.webp
  client/app/src/assets/main.css
  client/app/src/components/HelloWorld.vue
  client/app/src/components/TheWelcome.vue
  client/app/src/components/WelcomeItem.vue
  client/app/src/components/browseAll/ingredientCard.vue
  client/app/src/components/homePage/ButtonComponent.vue
  client/app/src/components/homePage/IngredientSearch.vue
  client/app/src/components/homePage/ListItem.vue
  client/app/src/components/icons/IconCommunity.vue
  client/app/src/components/icons/IconDocumentation.vue
  client/app/src/components/icons/IconEcosystem.vue
  client/app/src/components/icons/IconSupport.vue
  client/app/src/components/icons/IconTooling.vue
  client/app/src/router/index.js
  client/app/src/views/HomePage.vue
  client/app/src/views/HomeView.vue
Labels: Low Risk

#99 95 integrate home with browse
  .gitignore
  client/app/package-lock.json
  client/app/src/App.vue
  client/app/src/assets/bred1test.jpg
  client/app/src/components/browseAll/ingredientCard.vue
  client/app/src/components/homePage/ButtonComponent.vue
  client/app/src/main.js
  client/app/src/router/index.js
  client/app/src/views/BrowseView.vue
  client/app/src/views/HomePage.vue
Labels: in progress, Under review, task

#107 Vue build fix
  client/app/src/App.vue
Labels: Complete, task

#106 Admin add recipe
  client/app/src/main.js
  client/app/src/router/index.js
  client/app/src/views/AddRecipe.vue
  client/app/src/views/RemoveRecipe.vue
Labels: task

#112 links working in order
  client/app/src/components/admin/LogOut.vue
  client/app/src/components/homePage/ButtonComponent.vue
  client/app/src/views/Admin.vue
Labels: task

#113 Fix links and buttons admin
  client/app/src/components/admin/BigButton.vue
  client/app/src/components/homePage/ButtonComponent.vue
  client/app/src/views/AddRecipe.vue
  client/app/src/views/Admin.vue
Labels: task

#123 Shopping list
  client/app/src/components/homePage/IngredientSearch.vue
  client/app/src/components/homePage/ShoppingList.vue
  client/app/src/views/HomePage.vue
Labels: todo, task

#141 Browse ingredients fixed grid
  client/app/src/App.vue
  client/app/src/components/browseAll/ingredientCard.vue
  client/app/src/router/index.js
  client/app/src/views/AddRecipe.vue
  client/app/src/views/BrowseView.vue
  client/app/src/views/RecipePage.vue
Labels: Complete, task

#146 Shopping list implementation
  client/app/package.json
  client/app/src/App.vue
  client/app/src/components/homePage/IngredientSearch.vue
  client/app/src/components/homePage/ListItem.vue
  client/app/src/components/homePage/ShoppingList.vue
  client/app/src/stores/ingridentsStore.js
  client/app/src/views/HomePage.vue
Labels: Low Risk

#164 Add embedded social media
  client/app/src/App.vue
  client/app/src/components/homePage/instagramPosts.vue
Labels: Under review

#166 TEMPLATE - View Recipe Page
  client/app/src/App.vue
  client/app/src/views/BrowseView.vue
  client/app/src/views/RecipePage.vue
Labels: task

#172 Adding hint to shopping list
  client/app/src/components/homePage/ShoppingList.vue
Labels: Low Risk

#176 Styling improvements
  client/app/src/App.vue
  client/app/src/components/admin/BigButton.vue
  client/app/src/components/admin/LogOut.vue
  client/app/src/components/homePage/AllergyNotice.vue
  client/app/src/components/homePage/ButtonComponent.vue
  client/app/src/components/homePage/ShoppingList.vue
  client/app/src/views/Admin.vue
  client/app/src/views/AdminLogin.vue
  client/app/src/views/HomePage.vue
Labels: task

#182 Recipe page backend frontend
  .gitignore
  client/app/src/assets/sadFace.png
  client/app/src/views/RecipePage.vue
Labels: 8, Story

#189 Added Select All to to recipe page
  client/app/src/views/RecipePage.vue
Labels: task
