Repository AgileGroup6/Agile-Project, pull requests merged in 2023-02, with the labels that each got.

#206 Finished RecipePage.vue
  client/app/src/views/RecipePage.vue
Labels: Complete

#208 Quick improvement to recipePage
  client/app/src/views/RecipePage.vue
Labels: Complete

#209 Browse recipes view
  client/app/src/components/browseRecipes/RecipeCard.vue
  client/app/src/router/index.js
  client/app/src/views/BrowseAllRecipes.vue
  client/app/src/views/HomePage.vue
Labels: Must, in progress, 3

#223 Added additional tests
  client/app/src/tests/RecipeStore.test.js
  client/app/src/tests/ingridentsstore.test.js
Labels: Low Risk

#226 Added one image automation to highlighted recipes and bug fix for shopping list watch
  client/app/src/components/homePage/FavouriteRecipe.vue
  client/app/src/components/homePage/ListItem.vue
  client/app/src/config.js
  client/app/src/stores/ingridentsStore.js
  client/app/src/views/HomePage.vue
Labels: High Risk

#249 [Quick Fix] Index not declared
  client/app/src/components/homePage/FavouriteRecipe.vue
Labels: Low Reward

#255 [Bug Fix] : removeRecipe api endpoint when id is not set
  server/app/api/removeRecipe.js
  server/app/db/delRecipe.js
Labels: bug fixes

#257 [BugFix] BrowseAllIngredients scales images
  client/app/src/components/browseRecipes/RecipeCard.vue
  client/app/src/components/homePage/AllergyNotice.vue
  client/app/src/components/homePage/IngredientSearch.vue
  client/app/src/views/AllergyPage.vue
Labels: bug fixes

#258 Added beginning to sidebar, Fixed recipe instruction box
  client/app/src/App.vue
  client/app/src/components/homePage/NavBar.vue
  client/app/src/views/RecipePage.vue
Labels: task

#265 adjusted setFeatured params
  server/app/api/setFeatured.js
Labels: bug fixes
